# Generated by Django 5.2.8 on 2026-05-06 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenceimmobiliere',
            name='region',
            field=models.CharField(blank=True, choices=[('adamaoua', 'Adamaoua'), ('centre', 'Centre'), ('est', 'Est'), ('extreme_nord', 'Extrême-Nord'), ('littoral', 'Littoral'), ('nord', 'Nord'), ('nord_ouest', 'Nord-Ouest'), ('ouest', 'Ouest'), ('sud', 'Sud'), ('sud_ouest', 'Sud-Ouest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, choices=[('adamaoua', 'Adamaoua'), ('centre', 'Centre'), ('est', 'Est'), ('extreme_nord', 'Extrême-Nord'), ('littoral', 'Littoral'), ('nord', 'Nord'), ('nord_ouest', 'Nord-Ouest'), ('ouest', 'Ouest'), ('sud', 'Sud'), ('sud_ouest', 'Sud-Ouest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processedevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('adamaoua', 'Adamaoua'), ('centre', 'Centre'), ('est', 'Est'), ('extreme_nord', 'Extrême-Nord'), ('littoral', 'Littoral'), ('nord', 'Nord'), ('nord_ouest', 'Nord-Ouest'), ('ouest', 'Ouest'), ('sud', 'Sud'), ('sud_ouest', 'Sud-Ouest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='region',
            field=models.CharField(blank=True, choices=[('adamaoua', 'Adamaoua'), ('centre', 'Centre'), ('est', 'Est'), ('extreme_nord', 'Extrême-Nord'), ('littoral', 'Littoral'), ('nord', 'Nord'), ('nord_ouest', 'Nord-Ouest'), ('ouest', 'Ouest'), ('sud', 'Sud'), ('sud_ouest', 'Sud-Ouest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_identified',
            field=models.BooleanField(default=False, help_text='True once the identity service has verified the CNI'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='pending_role',
            field=models.CharField(blank=True, default='', help_text='Desired role awaiting identity confirmation', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_auth_id',
            field=models.CharField(blank=True, help_text='UUID assigned by the authentication service', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='One-time token sent by email for account verification', unique=True),
        ),
    ]
