# -------------------
# Eureka service info
# -------------------
eureka.server=http://192.168.68.81:8761
service.name=user-service
service.port=8000

# -------------------
# Django config
# -------------------
SECRET_KEY=dev-secret-key
DEBUG=True
ALLOWED_HOSTS=127.0.0.1,localhost

# -------------------
# Database config
# -------------------
database.name=user_db
database.user=user_user
database.password=ebate124
database.host=localhost
database.port=5432

# -------------------
# RabbitMQ
# -------------------
rabbitmq.url=amqp://dreamhouse:dreamhouse@192.168.68.81:5672/%2f
